'use client';

import { useState } from 'react';
import { ClipboardCheck, FileText, MessagesSquare, ShieldCheck } from 'lucide-react';
import type { AssessmentConfidentiality, DiscoveryIntakeData, DiscoveryMutation, EvidenceSourceType } from '@/lib/discovery/types';
import { postJson } from '@/lib/client/api';

type IntakeMode = 'evidence' | 'interview' | 'assessment';

export function DiscoveryIntake({ initialData }: { initialData: DiscoveryIntakeData }) {
  const [data, setData] = useState(initialData); const [mode, setMode] = useState<IntakeMode>('evidence'); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function mutate(mutation: DiscoveryMutation, form: HTMLFormElement) {
    setPending(true); setMessage('');
    try { setData(await postJson<DiscoveryIntakeData>('/api/discovery', mutation, 'Discovery intake could not be saved.')); form.reset(); setMessage('Saved with tenant, provenance, and visibility boundaries intact.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Discovery intake could not be saved.'); }
    finally { setPending(false); }
  }
  return <section className="discovery-intake" aria-labelledby="discovery-intake-heading">
    <header><div><p className="eyebrow">Consultant intake</p><h2 id="discovery-intake-heading">Build the evidence base</h2><p>Capture what was said, observed, measured, or assessed before interpreting what it means.</p></div><div className="discovery-counts"><span><strong>{data.evidenceCount}</strong>Evidence</span><span><strong>{data.interviewCount}</strong>Interviews</span><span><strong>{data.assessmentCount}</strong>Assessments</span></div></header>
    <p className="privacy-invariant"><ShieldCheck aria-hidden="true" />Assessment responses are evidence, not diagnosis. Consent, confidentiality, and source context stay explicit.</p>
    <div className="intake-mode" role="tablist" aria-label="Discovery intake type">
      <button className={mode === 'evidence' ? 'active' : ''} type="button" role="tab" aria-selected={mode === 'evidence'} onClick={() => setMode('evidence')}><FileText aria-hidden="true" />Evidence</button>
      <button className={mode === 'interview' ? 'active' : ''} type="button" role="tab" aria-selected={mode === 'interview'} onClick={() => setMode('interview')}><MessagesSquare aria-hidden="true" />Interview</button>
      <button className={mode === 'assessment' ? 'active' : ''} type="button" role="tab" aria-selected={mode === 'assessment'} onClick={() => setMode('assessment')}><ClipboardCheck aria-hidden="true" />Assessment</button>
    </div>
    {mode === 'evidence' && <EvidenceForm pending={pending} onSave={mutate} />}
    {mode === 'interview' && <InterviewForm pending={pending} onSave={mutate} />}
    {mode === 'assessment' && <AssessmentForm pending={pending} onSave={mutate} />}
    {message && <p className="intake-message" role="status">{message}</p>}
    {data.recentItems.length > 0 && <div className="intake-recent"><p className="eyebrow">Recently captured</p>{data.recentItems.map((item) => <article key={item.id}><span>{item.kind}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div></article>)}</div>}
  </section>;
}

type Save = (mutation: DiscoveryMutation, form: HTMLFormElement) => Promise<void>;
function values(form: HTMLFormElement) { return new FormData(form); }
function text(form: FormData, name: string) { return String(form.get(name)); }
function EvidenceForm({ pending, onSave }: { pending: boolean; onSave: Save }) { return <form className="intake-form" onSubmit={(event) => { event.preventDefault(); const data = values(event.currentTarget); void onSave({ action: 'CAPTURE_EVIDENCE', sourceType: text(data, 'sourceType') as EvidenceSourceType, title: text(data, 'title'), provenanceContext: text(data, 'provenanceContext'), content: text(data, 'content'), relevanceNote: text(data, 'relevanceNote'), limitations: text(data, 'limitations') }, event.currentTarget); }}><label>Source type<select name="sourceType"><option value="UPLOADED_DOCUMENT">Document or artifact</option><option value="METRIC_SYSTEM">Metric or system record</option><option value="CONSULTANT_OBSERVATION">Consultant observation</option><option value="CLIENT_STATEMENT">Client statement</option><option value="OTHER">Other</option></select></label><label>Source title<input name="title" required placeholder="Leadership team charter · 2025" /></label><label className="wide">Provenance and collection context<textarea name="provenanceContext" required placeholder="Who supplied it, when, and under what circumstances?" /></label><label className="wide">Source excerpt or observation<textarea name="content" required placeholder="Record the source material without interpreting it." /></label><label>Why it is relevant<textarea name="relevanceNote" required /></label><label>Known limitations<textarea name="limitations" placeholder="Optional at initial capture" /></label><button className="primary-button" disabled={pending}>{pending ? 'Saving…' : 'Capture evidence'}</button></form>; }
function InterviewForm({ pending, onSave }: { pending: boolean; onSave: Save }) { return <form className="intake-form" onSubmit={(event) => { event.preventDefault(); const data = values(event.currentTarget); void onSave({ action: 'RECORD_INTERVIEW', participantLabel: text(data, 'participantLabel'), guideName: text(data, 'guideName'), question: text(data, 'question'), response: text(data, 'response'), consentRecorded: data.get('consentRecorded') === 'on' }, event.currentTarget); }}><label>Participant label<input name="participantLabel" required placeholder="Senior pastor" /></label><label>Interview guide<input name="guideName" required placeholder="Church health discovery interview" /></label><label className="wide">Question<textarea name="question" required /></label><label className="wide">Response or excerpt<textarea name="response" required /></label><label className="consent-check wide"><input name="consentRecorded" type="checkbox" required />Consent to retain this response has been recorded.</label><button className="primary-button" disabled={pending}>{pending ? 'Saving…' : 'Record interview'}</button></form>; }
function AssessmentForm({ pending, onSave }: { pending: boolean; onSave: Save }) { return <form className="intake-form" onSubmit={(event) => { event.preventDefault(); const data = values(event.currentTarget); void onSave({ action: 'CREATE_ASSESSMENT', name: text(data, 'name'), dimension: text(data, 'dimension'), prompt: text(data, 'prompt'), audience: text(data, 'audience'), opensAt: text(data, 'opensAt'), closesAt: text(data, 'closesAt'), confidentiality: text(data, 'confidentiality') as AssessmentConfidentiality }, event.currentTarget); }}><label>Instrument name<input name="name" required placeholder="Ministry Rhythm Discovery" /></label><label>Dimension<input name="dimension" required placeholder="Leadership sustainability" /></label><label className="wide">First prompt<textarea name="prompt" required placeholder="Our current ministry rhythm is sustainable for staff and volunteers." /></label><label>Audience<input name="audience" required placeholder="Pastoral staff and ministry leads" /></label><label>Confidentiality<select name="confidentiality"><option value="CONFIDENTIAL">Confidential</option><option value="IDENTIFIED">Identified</option><option value="ANONYMOUS">Anonymous · minimum cohort 3</option></select></label><label>Opens<input name="opensAt" type="datetime-local" required /></label><label>Closes<input name="closesAt" type="datetime-local" required /></label><p className="form-guidance wide">This creates a draft, versioned instrument and administration. It does not claim psychometric validation.</p><button className="primary-button" disabled={pending}>{pending ? 'Saving…' : 'Create assessment draft'}</button></form>; }
