import 'server-only';
import { createHash, randomBytes } from 'node:crypto';
import type { PortalSession } from '@/lib/portal/types'; import { createSupabaseServerClient } from '@/lib/supabase/server'; import { createSupabaseAdminClient } from '@/lib/supabase/admin'; import { fixtureAccessCenter, mutateFixtureAccess } from './fixtures'; import type { AccessCenterData, AccessMutation, AccessMutationResult } from './types';
export async function getAccessCenter(session: PortalSession): Promise<AccessCenterData> {
  if (session.fixture) return fixtureAccessCenter(session); const supabase = await createSupabaseServerClient();
  const [invitations, assessments] = await Promise.all([supabase.from('client_invitations').select('id,email,display_name,platform_role,invitation_status,expires_at').eq('organization_id', session.organization.id).eq('engagement_id', session.engagement.id).order('created_at', { ascending: false }), supabase.from('assessment_administrations').select('id,audience_description,confidentiality,administration_status,closes_at,instrument_version_id').eq('organization_id', session.organization.id).eq('engagement_id', session.engagement.id).in('administration_status', ['DRAFT', 'OPEN']).order('created_at', { ascending: false })]);
  if (invitations.error) throw new Error(invitations.error.message); if (assessments.error) throw new Error(assessments.error.message);
  const versionIds = (assessments.data ?? []).map((item) => item.instrument_version_id); const names = new Map<string, string>();
  if (versionIds.length) { const versions = await supabase.from('assessment_instrument_versions').select('id,instrument_id').in('id', versionIds); if (versions.error) throw new Error(versions.error.message); const instrumentIds = (versions.data ?? []).map((item) => item.instrument_id); const instruments = instrumentIds.length ? await supabase.from('assessment_instruments').select('id,name').in('id', instrumentIds) : { data: [], error: null }; if (instruments.error) throw new Error(instruments.error.message); const instrumentNames = new Map((instruments.data ?? []).map((item) => [item.id, item.name])); for (const version of versions.data ?? []) names.set(version.id, instrumentNames.get(version.instrument_id) ?? 'Assessment'); }
  return { organizationId: session.organization.id, engagementId: session.engagement.id, invitations: (invitations.data ?? []).map((item) => ({ id: item.id, email: item.email, displayName: item.display_name, role: item.platform_role, status: item.invitation_status, expiresAt: item.expires_at })), assessments: (assessments.data ?? []).map((item) => ({ id: item.id, name: names.get(item.instrument_version_id) ?? 'Assessment', audience: item.audience_description, confidentiality: item.confidentiality, status: item.administration_status, closesAt: item.closes_at })) };
}
export async function mutateAccess(session: PortalSession, mutation: AccessMutation, origin: string): Promise<AccessMutationResult> { if (session.role !== 'consultant') throw new Error('Consultant access is required.'); if (session.fixture) return mutateFixtureAccess(session, mutation, origin); return mutation.action === 'INVITE_CLIENT' ? inviteClient(session, mutation, origin) : createParticipantLink(session, mutation, origin); }
async function inviteClient(session: PortalSession, mutation: Extract<AccessMutation, { action: 'INVITE_CLIENT' }>, origin: string) { const supabase = await createSupabaseServerClient(); const expiresAt = new Date(Date.now() + 3600000).toISOString(); const { data: invitation, error: insertError } = await supabase.from('client_invitations').insert({ organization_id: session.organization.id, engagement_id: session.engagement.id, email: mutation.email, display_name: mutation.displayName, platform_role: mutation.role, expires_at: expiresAt, created_by: session.personId }).select('id').single(); if (insertError) throw new Error(insertError.message); const admin = createSupabaseAdminClient(); const redirectTo = `${origin}/auth/accept-invitation?invitationId=${invitation.id}`; let authUserId: string | undefined; const invited = await admin.auth.admin.inviteUserByEmail(mutation.email, { redirectTo, data: { display_name: mutation.displayName } }); if (invited.data.user) authUserId = invited.data.user.id; else { const users = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 }); const existing = users.data.users.find((user) => user.email?.toLowerCase() === mutation.email); if (existing) { const magicLink = await admin.auth.signInWithOtp({ email: mutation.email, options: { shouldCreateUser: false, emailRedirectTo: redirectTo } }); if (!magicLink.error) authUserId = existing.id; } } if (!authUserId) { await supabase.from('client_invitations').update({ invitation_status: 'DELIVERY_FAILED', failure_reason: invited.error?.message ?? 'Auth invitation did not return a user.' }).eq('id', invitation.id); throw new Error('The secure invitation could not be delivered. No client access was activated.'); } const { error: updateError } = await supabase.from('client_invitations').update({ auth_user_id: authUserId, invitation_status: 'SENT', sent_at: new Date().toISOString(), failure_reason: null }).eq('id', invitation.id); if (updateError) throw new Error(updateError.message); return getAccessCenter(session); }
async function createParticipantLink(session: PortalSession, mutation: Extract<AccessMutation, { action: 'CREATE_ASSESSMENT_LINK' }>, origin: string) { const supabase = await createSupabaseServerClient(); const { data: administration, error } = await supabase.from('assessment_administrations').select('id,confidentiality,closes_at').eq('id', mutation.administrationId).eq('organization_id', session.organization.id).eq('engagement_id', session.engagement.id).single(); if (error || !administration) throw new Error('Assessment administration is outside the active engagement.'); if (administration.confidentiality === 'ANONYMOUS' && (mutation.recipientName || mutation.recipientEmail)) throw new Error('Anonymous links cannot retain a participant name or email.'); const token = randomBytes(32).toString('base64url'); const tokenHash = createHash('sha256').update(token).digest('hex'); const closesAt = new Date(administration.closes_at); const expiresAt = new Date(Math.min(closesAt.getTime(), Date.now() + 14 * 86400000)).toISOString(); const admin = createSupabaseAdminClient(); const { error: issueError } = await admin.rpc('issue_assessment_participant_link', { p_organization_id: session.organization.id, p_engagement_id: session.engagement.id, p_administration_id: administration.id, p_token_hash: tokenHash, p_respondent_person_id: null, p_recipient_name: mutation.recipientName ?? null, p_recipient_email: mutation.recipientEmail ?? null, p_expires_at: expiresAt, p_created_by: session.personId }); if (issueError) throw new Error(issueError.message); return { ...(await getAccessCenter(session)), participantUrl: `${origin}/assessment/${token}` }; }
