'use client';

import { useState, useTransition, type FormEvent, type ReactNode } from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileSearch, LockKeyhole, Plus, Route, ShieldCheck, Sparkles, Users } from 'lucide-react';
import type { OperationalEngagementData, OperationalSection } from '@/lib/operational-ai/types';

const engagementDateTime = new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' });

export function OperationalEngagementCenter({ initialData, section }: { initialData: OperationalEngagementData; section: OperationalSection }) {
  const [data, setData] = useState(initialData); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState('');
  function mutate(payload: Record<string, unknown>, form?: HTMLFormElement) {
    startTransition(async () => {
      setMessage('');
      try {
        const response = await fetch('/api/operational-ai', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) });
        const body = await response.json();
        if (!response.ok) { setMessage(body.error ?? 'The workspace could not be updated.'); return; }
        setData(body); form?.reset(); setMessage('Workspace updated.');
      } catch {
        setMessage('The workspace could not be reached. Try again.');
      }
    });
  }
  const product = (id?: string) => data.products.find((item) => item.id === id)?.name ?? 'Engagement-wide';

  return <section className="operational-center" aria-label="Operational Product AI engagement workspace">
    <div className="handling-banner"><ShieldCheck aria-hidden="true" /><div><strong>{data.handlingLabel}</strong><span>{data.handlingNotice}</span></div></div>
    {message && <p className={message === 'Workspace updated.' ? 'operational-message' : 'operational-message error'} role="status">{message}</p>}
    {section === 'overview' && <Overview data={data} />}
    {section === 'products' && <><SectionHeader icon={<FileSearch />} title="Product register" copy="Define the sanitized products whose purpose, workflow, quality criteria, and human judgment will be assessed." /><CardGrid>{data.products.map((item) => <RecordCard key={item.id} eyebrow={item.status} title={item.name}><p>{item.description}</p><Meta rows={[['Owner', item.ownerLabel], ['Handling', item.handlingLabel]]} /></RecordCard>)}</CardGrid><AddForm title="Add product" onSubmit={(values, form) => mutate({ action: 'ADD_PRODUCT', ...values }, form)} pending={pending}><Field name="name" label="Product name" /><Field name="ownerLabel" label="Product owner" /><Field name="description" label="Sanitized purpose and scope" wide multiline /></AddForm></>}
    {section === 'audits' && <><SectionHeader icon={<ClipboardCheck />} title="Written audits" copy="Collect structured product-owner, analyst, and reviewer perspectives before interviews. Responses are evidence—not diagnosis." /><CardGrid>{data.audits.map((item) => <RecordCard key={item.id} eyebrow={item.status.replaceAll('_', ' ')} title={item.title}><p>{product(item.productId)}</p><Meta rows={[['Respondent', item.respondentLabel], ['Due', item.dueOn], ['Progress', `${item.completedResponses} of ${item.totalPrompts}`]]} /><label className="inline-control">Workflow status<select value={item.status} disabled={pending} onChange={(event) => mutate({ action: 'UPDATE_AUDIT_STATUS', id: item.id, status: event.target.value })}><option>NOT_STARTED</option><option>IN_PROGRESS</option><option>SUBMITTED</option><option>REVIEWED</option></select></label></RecordCard>)}</CardGrid></>}
    {section === 'interviews' && <><SectionHeader icon={<Users />} title="Interview workspace" copy="Schedule role-specific conversations, keep product context visible, and preserve the distinction between participant response and consultant interpretation." /><CardGrid>{data.interviews.map((item) => <RecordCard key={item.id} eyebrow={item.status} title={item.participantLabel}><p>{item.objective}</p><Meta rows={[['Product', product(item.productId)], ['Guide', item.interviewType.replaceAll('_', ' ')], ['Scheduled', formatDateTime(item.scheduledFor)], ['Notes', String(item.notesCount)]]} /></RecordCard>)}</CardGrid><AddForm title="Schedule interview" onSubmit={(values, form) => mutate({ action: 'ADD_INTERVIEW', ...values }, form)} pending={pending}><ProductField products={data.products} /><Field name="participantLabel" label="Participant / role label" /><Field name="interviewType" label="Interview guide" defaultValue="PRODUCT_OWNER" /><Field name="scheduledFor" label="Date and time" type="datetime-local" /><Field name="objective" label="Sanitized interview objective" wide multiline /></AddForm></>}
    {section === 'workflows' && <><SectionHeader icon={<Route />} title="Current-state workflow maps" copy="Make handoffs, delays, rework, judgment, and verification visible before evaluating any AI opportunity." />{data.workflows.map((workflow) => <section className="operational-workflow" key={workflow.id}><header><div><span className="status-chip">{workflow.status}</span><h3>{workflow.name}</h3><p>{workflow.purpose}</p></div><strong>{product(workflow.productId)}</strong></header><ol>{workflow.steps.map((step) => <li key={step.id}><span className="step-number">{String(step.sequence).padStart(2, '0')}</span><div><h4>{step.name}</h4><p>{step.inputs} <ArrowRight aria-hidden="true" /> {step.outputs}</p><Meta rows={[['Owner', step.ownerLabel], ['Tool', step.systemTool], ['Active / wait', `${step.durationMinutes}m / ${step.waitMinutes}m`], ['Rework', step.reworkRisk], ['Judgment', step.judgmentRequired], ['Verification', step.verificationRequired]]} /><label className="inline-control">AI suitability — human reviewed<select value={step.aiSuitability} disabled={pending} onChange={(event) => mutate({ action: 'UPDATE_STEP_SUITABILITY', id: step.id, aiSuitability: event.target.value })}><option>NOT_ASSESSED</option><option>ASSISTIVE_CANDIDATE</option><option>HUMAN_ONLY</option></select></label></div></li>)}</ol></section>)}</>}
    {section === 'evidence' && <><SectionHeader icon={<FileSearch />} title="Evidence and observations" copy="Capture what exists and what was observed with a reviewable source locator. Meaning and recommendations belong in later epistemic objects." /><CardGrid>{data.evidence.map((item) => <RecordCard key={item.id} eyebrow={`${item.sourceType} · ${item.status}`} title={item.title}><p>{item.observation}</p><Meta rows={[['Product', product(item.productId)], ['Source', item.sourceLocator], ['Visibility', item.visibility.replaceAll('_', ' ')]]} /></RecordCard>)}</CardGrid><AddForm title="Capture evidence" onSubmit={(values, form) => mutate({ action: 'ADD_EVIDENCE', ...values }, form)} pending={pending}><ProductField products={data.products} optional /><Field name="title" label="Evidence title" /><SelectField name="sourceType" label="Source type" values={['DOCUMENT', 'INTERVIEW', 'AUDIT', 'WORKFLOW', 'OBSERVATION']} /><SelectField name="visibility" label="Visibility" values={['CONSULTANT_PRIVATE', 'ENGAGEMENT_SHARED']} /><Field name="sourceLocator" label="Reviewable source locator" /><Field name="observation" label="What was observed or recorded" wide multiline /></AddForm></>}
    {section === 'documents' && <><SectionHeader icon={<FileSearch />} title="Artifact requests" copy="Track what was requested without treating files as received until they are actually available and authorized for this environment." /><CardGrid>{data.requests.map((item) => <RecordCard key={item.id} eyebrow={item.status} title={item.title}><p>{item.handlingNote}</p><Meta rows={[['Product', product(item.productId)], ['Requested from', item.requestedFrom], ['Due', item.dueOn]]} /></RecordCard>)}</CardGrid><AddForm title="Request artifact" onSubmit={(values, form) => mutate({ action: 'ADD_REQUEST', ...values }, form)} pending={pending}><ProductField products={data.products} optional /><Field name="title" label="Requested artifact" /><Field name="requestedFrom" label="Requested from" /><Field name="dueOn" label="Due date" type="date" /></AddForm></>}
    {section === 'actions' && <><SectionHeader icon={<CheckCircle2 />} title="Engagement actions" copy="Keep ownership and due dates explicit. Consultant-private actions remain outside the client view." /><CardGrid>{data.actions.map((item) => <RecordCard key={item.id} eyebrow={item.status.replaceAll('_', ' ')} title={item.title}><Meta rows={[['Owner', item.ownerLabel], ['Due', item.dueOn], ['Visibility', item.visibility.replaceAll('_', ' ')]]} /><label className="inline-control">Status<select value={item.status} disabled={pending} onChange={(event) => mutate({ action: 'UPDATE_ACTION_STATUS', id: item.id, status: event.target.value })}><option>OPEN</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>CANCELLED</option></select></label></RecordCard>)}</CardGrid><AddForm title="Add action" onSubmit={(values, form) => mutate({ action: 'ADD_ACTION', ...values }, form)} pending={pending}><Field name="title" label="Action" wide /><Field name="ownerLabel" label="Owner" /><Field name="dueOn" label="Due date" type="date" /><SelectField name="visibility" label="Visibility" values={['CONSULTANT_PRIVATE', 'ENGAGEMENT_SHARED']} /></AddForm></>}
    {['findings', 'opportunities'].includes(section) && <PhaseGate phase="Analysis phase" title="This workspace opens after evidence collection." copy="Findings and opportunities will require explicit evidence links, alternative interpretations, unanswered questions, and human review. P0 does not auto-diagnose the organization." />}
    {['prototypes', 'validation', 'recommendations'].includes(section) && <PhaseGate phase="Prototype and validation phase" title="This workspace opens after opportunities are reviewed." copy="Prototype criteria, human-in-the-loop controls, baseline comparisons, validation evidence, and recommendations remain gated until the engagement reaches that phase." />}
  </section>;
}

function Overview({ data }: { data: OperationalEngagementData }) { const complete = data.actions.filter((item) => item.status === 'COMPLETED').length; return <><section className="operational-hero"><div><span className="status-chip gold">{data.currentStage}</span><h2>{data.engagementName}</h2><p>{data.objective}</p></div><dl><div><dt>Owner</dt><dd>{data.ownerLabel}</dd></div><div><dt>Target completion</dt><dd>{data.targetCompletion}</dd></div><div><dt>Engagement boundary</dt><dd>Consulting and evidence system</dd></div></dl></section><section className="operational-metrics"><Metric value={data.products.length} label="Products in scope" /><Metric value={data.audits.filter((item) => item.status !== 'NOT_STARTED').length} label="Audits started" /><Metric value={data.interviews.length} label="Interviews planned" /><Metric value={data.evidence.length} label="Evidence items" /><Metric value={`${complete}/${data.actions.length}`} label="Actions complete" /></section><section className="operational-scope"><div><p className="eyebrow">ENGAGEMENT SCOPE</p><h3>Responsible transformation starts with disciplined inquiry.</h3><p>{data.scopeStatement}</p></div><ul><li><CheckCircle2 />Assess sanitized product workflows and quality criteria</li><li><CheckCircle2 />Identify bottlenecks, handoffs, rework, and judgment points</li><li><CheckCircle2 />Preserve evidence provenance and visibility</li><li><AlertTriangle />No autonomous operational agents or mission planning</li><li><AlertTriangle />No controlled or operational data in this environment</li></ul></section></> }
function SectionHeader({ icon, title, copy }: { icon: ReactNode; title: string; copy: string }) { return <header className="operational-section-header"><span>{icon}</span><div><p className="eyebrow">SEE REALITY · P0</p><h2>{title}</h2><p>{copy}</p></div></header> }
function CardGrid({ children }: { children: ReactNode }) { return <div className="operational-card-grid">{children}</div> }
function RecordCard({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <article className="operational-record"><span className="status-chip">{eyebrow}</span><h3>{title}</h3>{children}</article> }
function Meta({ rows }: { rows: Array<[string, string]> }) { return <dl className="operational-meta">{rows.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl> }
function Metric({ value, label }: { value: string | number; label: string }) { return <div><strong>{value}</strong><span>{label}</span></div> }
function PhaseGate({ phase, title, copy }: { phase: string; title: string; copy: string }) { return <section className="phase-gate"><Sparkles aria-hidden="true" /><p className="eyebrow">{phase}</p><h2>{title}</h2><p>{copy}</p><span><LockKeyhole aria-hidden="true" /> Deliberately gated—no hidden automation is running.</span></section> }
function AddForm({ title, children, pending, onSubmit }: { title: string; children: ReactNode; pending: boolean; onSubmit: (values: Record<string, string>, form: HTMLFormElement) => void }) { return <details className="operational-add"><summary><Plus aria-hidden="true" />{title}</summary><form onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; onSubmit(Object.fromEntries(new FormData(form).entries()) as Record<string, string>, form); }}>{children}<p className="form-guidance">Use sanitized process-level information only. Records remain inside this engagement and its selected visibility scope.</p><button className="primary-button" disabled={pending}>{pending ? 'Saving…' : 'Save'}</button></form></details> }
function Field({ name, label, wide = false, multiline = false, type = 'text', defaultValue }: { name: string; label: string; wide?: boolean; multiline?: boolean; type?: string; defaultValue?: string }) { return <label className={wide ? 'wide' : ''}>{label}{multiline ? <textarea name={name} required defaultValue={defaultValue} /> : <input name={name} type={type} required defaultValue={defaultValue} />}</label> }
function SelectField({ name, label, values }: { name: string; label: string; values: string[] }) { return <label>{label}<select name={name}>{values.map((value) => <option key={value}>{value}</option>)}</select></label> }
function ProductField({ products, optional = false }: { products: OperationalEngagementData['products']; optional?: boolean }) { return <label>Product{optional && ' (optional)'}<select name="productId" required={!optional}>{optional && <option value="">Engagement-wide</option>}{products.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label> }
function formatDateTime(value: string) { return engagementDateTime.format(new Date(value)) }
