import type { HandoffChecklistItem, MinistryHandoffStatus, MinistryReadiness, SaveMinistryHandoffInput } from './types';
const readiness: MinistryReadiness[] = ['NOT_ASSESSED', 'FOUNDATIONAL', 'PREPARING', 'READY', 'OPERATING']; const statuses: MinistryHandoffStatus[] = ['DRAFT', 'READY_FOR_REVIEW', 'READY_FOR_SETUP', 'COMPLETED'];
export const defaultHandoffChecklist: HandoffChecklistItem[] = [
  { key: 'ADMIN_CONFIRMED', label: 'Authorized Ministry OS administrator confirmed', complete: false, ordinal: 1 },
  { key: 'LEADERS_MAPPED', label: 'Ministry areas and leaders mapped', complete: false, ordinal: 2 },
  { key: 'PRIORITIES_CONFIRMED', label: 'Initial operating priorities confirmed', complete: false, ordinal: 3 },
  { key: 'RHYTHM_DEFINED', label: 'Meeting and planning rhythm defined', complete: false, ordinal: 4 },
  { key: 'WORKFLOWS_SELECTED', label: 'First events and workflows selected', complete: false, ordinal: 5 },
  { key: 'GUIDED_SETUP_COMPLETE', label: 'Consultant-guided Ministry OS setup completed', complete: false, ordinal: 6 },
];
export function validateMinistryHandoff(value: unknown): SaveMinistryHandoffInput { if (!value || typeof value !== 'object') throw new Error('Handoff details are required.'); const input = value as Record<string, unknown>; const text = (key: string) => typeof input[key] === 'string' ? input[key].trim() : ''; const churchName = text('churchName'); if (!churchName) throw new Error('Church name is required.'); const selectedReadiness = text('readiness') as MinistryReadiness; const status = text('status') as MinistryHandoffStatus; if (!readiness.includes(selectedReadiness) || !statuses.includes(status)) throw new Error('Handoff readiness or status is invalid.'); const checklist = Array.isArray(input.checklist) ? input.checklist.map((item, index) => { const row = item as Record<string, unknown>; const key = typeof row.key === 'string' ? row.key : ''; const label = typeof row.label === 'string' ? row.label.trim() : ''; if (!/^[A-Z][A-Z0-9_]*$/.test(key) || !label) throw new Error('Checklist item is invalid.'); return { key, label, complete: row.complete === true, ordinal: index + 1 }; }) : defaultHandoffChecklist; return { churchName, authorizedAdminName: text('authorizedAdminName'), authorizedAdminEmail: text('authorizedAdminEmail').toLowerCase(), ministryAreasAndLeaders: text('ministryAreasAndLeaders'), priorities: text('priorities'), meetingAndPlanningRhythm: text('meetingAndPlanningRhythm'), eventsAndWorkflows: text('eventsAndWorkflows'), readiness: selectedReadiness, status, checklist }; }
