'use client';

import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import { consultingIntakeQuestions } from '@/lib/prospects/types';

export function PublicIntake() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>(Array(consultingIntakeQuestions.length).fill('')); const [contact, setContact] = useState({ firstName: '', email: '', organizationName: '', roleTitle: '', newsletterOptIn: false }); const [message, setMessage] = useState(''); const complete = step === consultingIntakeQuestions.length;
  async function submit() {
    setMessage('');
    try {
      const response = await fetch('/api/prospects/intake', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...contact, responses: consultingIntakeQuestions.map((question, index) => ({ questionKey: question.key, prompt: question.prompt, answer: answers[index] })) }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error); setStep(consultingIntakeQuestions.length + 1);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Your intake could not be saved.'); }
  }
  if (step > consultingIntakeQuestions.length) return <main className="prospect-intake"><section className="intake-card completion"><span className="intake-mark"><Check aria-hidden="true" /></span><p className="eyebrow">Thank you</p><h1>You&apos;ve given us enough to begin.</h1><p>Lead Emergence will review what you shared and identify signals worth examining, possibilities for focused change, and a useful first move.</p><p>Your 3-2-1 is reviewed by a human before it is sent. We&apos;ll follow up using the contact information you provided.</p><small>PRODUCTIVITY IS ONE OUTCOME. LEADERSHIP IS THE PURPOSE.</small></section></main>;
  if (complete) return <main className="prospect-intake"><section className="intake-card"><p className="eyebrow">One final step</p><h1>Where should we follow up?</h1><label>First name<input value={contact.firstName} onChange={(event) => setContact({ ...contact, firstName: event.target.value })} autoComplete="given-name" /></label><label>Email<input type="email" value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })} autoComplete="email" /></label><label>Organization <small>Optional</small><input value={contact.organizationName} onChange={(event) => setContact({ ...contact, organizationName: event.target.value })} /></label><label>Role <small>Optional</small><input value={contact.roleTitle} onChange={(event) => setContact({ ...contact, roleTitle: event.target.value })} /></label><label className="check-label"><input type="checkbox" checked={contact.newsletterOptIn} onChange={(event) => setContact({ ...contact, newsletterOptIn: event.target.checked })} /> Send me occasional Lead Emergence insights on leadership, AI, and organizational transformation.</label><div className="intake-actions"><button className="secondary-button" onClick={() => setStep(step - 1)}><ArrowLeft aria-hidden="true" /> Back</button><button className="primary-button" onClick={() => void submit()}>Complete intake <ArrowRight aria-hidden="true" /></button></div>{message && <p role="alert">{message}</p>}</section></main>;
  const question = consultingIntakeQuestions[step]; const canContinue = answers[step].trim().length >= 8;
  return <main className="prospect-intake"><section className="intake-card"><p className="intake-progress" aria-live="polite">Question {step + 1} of {consultingIntakeQuestions.length}</p><div className="intake-progress-line"><span style={{ width: `${((step + 1) / consultingIntakeQuestions.length) * 100}%` }} /></div><p className="eyebrow">Start with your reality</p><h1>{question.prompt}</h1><label className="sr-only" htmlFor="intake-answer">Your response</label><textarea id="intake-answer" value={answers[step]} onChange={(event) => setAnswers(answers.map((answer, index) => index === step ? event.target.value : answer))} placeholder="Take a moment. There is no perfect answer." rows={6} autoFocus /><div className="intake-actions">{step > 0 ? <button className="secondary-button" onClick={() => setStep(step - 1)}><ArrowLeft aria-hidden="true" /> Back</button> : <span /> }<button className="primary-button" disabled={!canContinue} onClick={() => setStep(step + 1)}>Continue <ArrowRight aria-hidden="true" /></button></div></section></main>;
}